### ISSUE TITLE
geometry option seems to have no effect

### ISSUE THREAD

**Issue by bajanine** [arnoldrobbins/9menu#1]
It seems that 9menu ignores the geometry option on Debian Jessie with Mate unless I am missing something obvious. :)
`9menu -geometry 50*50 -fg black -bg green ...`

Regardless of geometry settings the location does not change.

/edit
Well, I don't know what the heck happened after a reboot all is good!

**Comment by arnoldrobbins** [comment]
Hi. Thanks for your mail.

bajanine notifications@github.com wrote:

> It seems that 9menu ignores the geometry option on Debian Jessie with
> Mate unless I am missing something obvious. :)
> `9menu -geometry 50*50 -fg black -bg green ...`
> 
> Regardless of geometry settings the location does not change.

I think this is a Mate issue. I see this on both Debian and Ubuntu Mate
16.04.  But the 9menu code hasn't changed.

As I understand it, the window manager can ignore the geometry calls
made by an application and it seems pretty clear that that is what's
going on here.

Thanks,

Arnold
