### ISSUE TITLE
font size; suitable fonts; examples of setting font AND size

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [arnoldrobbins/9menu#4]
@arnoldrobbins This is putting in an at line automatically. Anyway:
How can I set a larger font size?
Can you give some examples?
Do I limit myself to fonts xfontsel can find or some other subset of  fonts on the system or what? Just trial and error?

**Comment by ghost** [comment]
You use the -font option and name any font that the X server knows about.

**Comment by Lew-Rockwell-Fan** [comment]
Thanks. I got:
-font "-*-fixed-bold-r-normal-*-64-*-*-*-*-*-*-*"
to work. Cool program. A lot lighter than gxmessage. I'll put something about this in the wiki if you have no objection. Examples help. I'd love to use a better looking font, but that serves. I don't know anything better than to stumble through xfontsel.
