### ISSUE TITLE
What about using Meson?

### ISSUE THREAD

**Issue by AndersonTorres** [arnoldrobbins/9menu#5]
I have tried to build 9menu using xmkmf, but it complained about not finding 9menu.man

So I wrote a simple `meson.build` file:

```meson
# meson.build for 9menu
# license: public domain
project ('9menu', 'c')

executable ('9menu', '9menu.c',
            install: true,
            dependencies: [ dependency('x11'),
                            dependency('xext') ])
install_man ('9menu.1')
```

And it compiled just fine.

**Comment by arnoldrobbins** [comment]
Hi. Thanks for the note.

9menu was mainly designed to work with Imake and not particularly xmkmf.

Given that there is already a simple Makefile in the repo, I don't see a burning reason to support Yet Another Build System, especially as I've never even heard of meson.  What do I get with meson that I don't get with make?

**Comment by AndersonTorres** [comment]
Well, the only advantage I can point is the autodetection, especially in the case the X11 libraries are not in standard locations (and a mere `-lX11` does not suffice).

**Comment by arnoldrobbins** [comment]
OK. I have added the meson.build file.  Thanks.
