### ISSUE TITLE
menitem starting with - in a file fails with usage error

### ISSUE THREAD

**Issue by Framsfex** [arnoldrobbins/9menu#7]
I tried to use "-------" (as a delimiter sign) as a menitem in a file, but this leads to error usage:

framstag@juhu:~:  9menu -popup -file /home/framstag/.9menu/main
usage: 9menu [-display displayname] [-font fname] [-file filename] [-path][-geometry geom] [-shell shell] [-label name] [-popup] [-popdown] [-iconic] [-teleport] [-warp] [-version] menitem:command ...

framstag@juhu:~: cat /home/framstag/.9menu/main
xxterm:exec xxterm
mutt:exec xxterm -e mutt -R
chromium
thunar
[ssh]:exec 9mm ssh
-------
xkill
xfce4-settings-manager
xfce4-about
chvt 1
logout:xfce4-session-logout
exit

I suspect 9menu parses the content of a file as arguments, which makes no sense.

Best solution (for me) would be a dedicated not-cklickable delimiter symbol similar to HML <hr>

**Comment by arnoldrobbins** [comment]
The man page is clear that `-file` treats the contents of the file as menu items and additional arguments.  That has been the behavior for a long time and isn't going to change.  You could try a delimiter like `====:true &` instead.  Thanks.

**Comment by Framsfex** [comment]
On Fri 2023-02-03 (00:41), Arnold Robbins wrote:

> The man page is clear that `-file` treats the contents of the file as
> menu items and additional arguments.  That has been the behavior for a
> long time and isn't going to change. 

Ehh... one should read the documentation first before complaining :-}
Sorry.


> You could try a delimiter like `====:true &` instead.

Good suggestion!

But why the "&"?
It works for me without it.


-- 
Ullrich Horlacher              Server und Virtualisierung
Rechenzentrum TIK
Universitaet Stuttgart         E-Mail: ***@***.***
Allmandring 30a                Tel:    ++49-711-68565868
70569 Stuttgart (Germany)      WWW:    http://www.tik.uni-stuttgart.de/
***@***.***>
