### ISSUE TITLE
menu stops being visible under Openbox

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [arnoldrobbins/9menu#9]
I realize Openbox is not the target environment, but if anyone has suggestions I'd appreciate them, because 9menu works well for me generally & would be perfect for what I want to do in this case if the menu would quit spontaneously hiding. This is under a plain Openbox under a light Ubuntu 18.04 built up from the mini.iso.
This command gives a menu:
`9menu -label 'viewnior image - persistent floating 9menu' -font "-*-dejavu sans-medium-r-*-*-40-*-*-*-*-*-*-*" -bg "#000000" -fg "#ffffff" rename 'move to' 'copy to' "<---> flip" "^v flip" "90 Right" 180 '90 Left' junk exit`
but it disappears after a while without any evident reason.
wmctrl -l shows it's still running & wmctrl -a will make it visible again, but it doesn't show up on Openbox's menu of running windows (kind of like a task bar).
My Openbox rc.xml has 2 stanzas, which should keep it visible, but don't. Code tags chopped off the first of this for some reason so I'll try multiple pastes:
`<application class="9menu">`
`      <decor>yes</decor>`
`      <focus>yes force="yes"</focus>`
`      <layer>above force="yes"</layer>`
`      <maximized>no</maximized>`
`      <skip_taskbar>no</skip_taskbar>`
`	<iconic>no</iconic>`
`	<skip_pager>no</skip_pager>`
`	<skip_taskbar>no</skip_taskbar>`
`    </application>`
And this one specific for the window should take precedence:
`<application title="viewnior image - persistent floating 9menu">`
`      <decor>no</decor>`
`      <focus>no</focus>`
`      <layer>above force="yes"</layer>`
`      <maximized>no</maximized>`
`      <skip_taskbar>no</skip_taskbar> `
`    </application>`

**Comment by Lew-Rockwell-Fan** [comment]
For anybody with a similar problem, this is a good work around. Follow the menu command with:
while [ "$(wmctrl -l|grep " title$")" = '' ]; do
	sleep 0.3
done
wmctrl -r "title" -b remove,hidden
wmctrl -r "title" -b add,above

**Comment by arnoldrobbins** [comment]
This would very much seem to be an issue with Openbox, as the 9menu code hasn't changed in a long time.  (Of course, if someone has a fix for 9menu itself, let me know.) I'm glad you found a workaround. I am closing this issue.
